# WAS server setting
server:
  port: 8080
  servlet:
    context-path: /
 
devtools: 
  livereload:
    enabled:  true

spring:
  redis:
    host: 192.168.56.101
    port: 6379
    
project:  
  basePackage:  com.bskim.co